spring:
  application:
    name: user-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://127.0.0.1:15432/user_db
server:
  port: 8086
  servlet:
    context-path: /api/v1/user

keycloak:
  server-url: http://keycloak:8443
  realm: pizzeria
  resource: pizzeria-app
  credentials:
    secret: yWouqgKVJ5yIMnpZLQYBb1lPyNjMYTlv