spring:
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 20
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000
  datasource:
    url: jdbc:postgresql://postgres:5432/pizzeria_db
    username: postgres
    password: password