spring:
  config:
    import: "optional:configserver:http://localhost:8888"
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      database: 2
      connect-timeout: 2s
      timeout: 5s
      lettuce:
        pool:
          min-idle: 1
          max-idle: 5
          max-active: 20
  datasource:
    url: jdbc:postgresql://localhost:15432/order_db
    username: postgres
    password: password

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.data.redis.cache: TRACE

menu-service:
  url: "http://localhost:8081"
